public_address: "192.168.0.100"
db_port: 8080
mysql_dsn: "root:123456@tcp(127.0.0.1:3306)/douyin?charset=utf8&parseTime=True&loc=Local"
local_video_path: "./public/"
remote_video_path: "static"   # relative path
redis_address: "10.112.83.133"
rdb_port: 6379
rdb_pwd: "" #Redis数据库密码
rbd_num: 0 #使用Redis的哪个数据库，默认0
rdb_pool_size: 100 #连接池大小